
@HOST = {{$dotenv HOST}}
@PORT_AUTH = 3000
@PORT = 4000

###
# @name login
POST {{HOST}}:{{PORT_AUTH}}/login
Content-Type: application/json

{
    "username": "{{$dotenv USER}}",
    "password":  "{{$dotenv PASSWORD}}"
}

### Book Internal
@TOKEN = {{login.response.body.$.accessToken}}
POST {{HOST}}:{{PORT}}/books
Authorization: Bearer {{TOKEN}}
